name: nero
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23,<3
  - h5py>=3.11
  - pyyaml>=6.0
  - opencv
  - matplotlib>=3.7
  - mujoco>=3.3,<4
  - pinocchio>=3,<4
  - scipy>=1.10,<2
